import streamlit as st
import os
import streamlit.components.v1 as components

st.set_page_config(page_title="Management Dashboard", layout="wide")

st.title("CEO Daily Report - Management Dashboard")

# Read reports from a directory
REPORTS_DIR = "reports"
os.makedirs(REPORTS_DIR, exist_ok=True)

with st.sidebar:
    st.header("Upload New Report")
    uploaded_file = st.file_uploader("Upload HTML Report", type=["html"])
    if uploaded_file is not None:
        file_path = os.path.join(REPORTS_DIR, uploaded_file.name)
        with open(file_path, "wb") as f:
            f.write(uploaded_file.getbuffer())
        st.success(f"Uploaded {uploaded_file.name}")

report_files = [f for f in os.listdir(REPORTS_DIR) if f.endswith('.html')]
report_files.sort(reverse=True) # Show newest first

if not report_files:
    st.info("No reports found. Please use the sidebar on the left to upload a report generated by the CEO Daily Report App.")
else:
    selected_report = st.sidebar.selectbox("Select Report to View", report_files)
    
    if selected_report:
        st.subheader(f"Viewing: {selected_report}")
        with open(os.path.join(REPORTS_DIR, selected_report), "r", encoding="utf-8") as f:
            html_content = f.read()
            
        # Display the HTML
        components.html(html_content, height=1000, scrolling=True)
